language: php
php:
    - 5.6
    - 5.5
    - hhvm
    
install:
    - composer require satooshi/php-coveralls:~0.6@stable
    
before_script:
    - mkdir -p build/logs
    
script: 
    - phpunit --configuration phpunit.xml.dist --coverage-text
    
after_success:
    - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'