checks:
    php:
        code_rating: true
        duplication: true

tools:
    external_code_coverage:
        timeout: 1800
    php_code_sniffer:
        filter:
            excluded_paths:
                - "tests/*"
                - 'bootstrap.php'
                - 'app.php'
        config:
            standard: "PSR2"
    php_cs_fixer:
        filter:
            excluded_paths:
                - "tests/*"
                - 'bootstrap.php'
                - 'app.php'
        config:
            level: "psr2"
    php_sim:
        enabled: true
        min_mass: 16
        filter:
            excluded_paths:
                - 'tests/*'
                - 'bootstrap.php'
                - 'app.php'
            paths: {  }
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            excluded_paths:
                - 'tests/*'
                - 'bootstrap.php'
                - 'app.php'
            paths: {  }
    php_analyzer:
        enabled: true
        extensions:
            - php
        dependency_paths: {  }
        filter:
            excluded_paths:
                - 'tests/*'
                - 'bootstrap.php'
                - 'app.php'
            paths: {  }
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            excluded_paths:
                - 'tests/*'
                - 'bootstrap.php'
                - 'app.php'
            paths: {  }
filter:
    excluded_paths:
        - 'tests/*'
        - 'bootstrap.php'
        - 'app.php'
    paths: {  }
build_failure_conditions:
    - 'project.metric("scrutinizer.quality", < 9)'
    - 'project.metric("scrutinizer.test_coverage", < 0.75)'
    - 'elements.rating(<= D).new.exists'
