sudo: false
language: php
php:
- 5.6
- 5.5
- hhvm
notifications:
  hipchat:
    rooms:
      secure: SEsg65FCsZiO+Ocmvw8+PBZ6QU3NrypIKr5OIm5uAbenW8zimNwxOye2QMvGwUMqYGcYfeZxc3j2tVOOXxCQYaRMXFtWu4Oao1EUlH6Vm7mt5xag+neDtA33GZK6NC9TzbRv+HR9PWIK452la7l5ImJkNj9FpXwM/7o8t3x8jbQ=
install:
- sh -c 'if [ ! -d vendor ]; then composer install --dev; fi;'
- wget https://scrutinizer-ci.com/ocular.phar
before_script:
- mkdir -p build/logs
- export COVERALLS_SERVICE_NAME=travis-pro
- export COVERALLS_REPO_TOKEN=2FJ2ccRuQxyEtOi46NabocjMzVhuwPloi
script:
- phpunit --configuration phpunit.xml.dist
after_script:
- phpunit --configuration phpunit.xml.dist --coverage-text | grep "Lines:" | grep
  -v "Methods:" > build/logs/coverageper.txt
- sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then php vendor/bin/coveralls -v; fi;'
- sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then php ocular.phar code-coverage:upload
  --access-token="6338e1a7beec477c62fcd1e96ca89a2372afafa2de6cb7c5a825431962bf01c5"
  --format=php-clover build/logs/clover.xml; fi;'
